language: php

php:
  - '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - bin
    - vendor

matrix:
  include:
    - php: 7.2
      env: DEPENDENCIES='low'

before_script:
  - composer selfupdate
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; fi;

script:
  - bin/phpunit
