language: php

php: [5.5, 5.6, 7.0, hhvm]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - bin
    - vendor

matrix:
  include:
    - php: 5.5
      env: DEPENDENCIES='low'

before_script:
  - composer selfupdate
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; fi;

script:
  - bin/phpunit
